#!/usr/bin/env python
# KlupuNG
# Copyright (C) 2014 Koodilehto Osk <http://koodilehto.fi>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

from __future__ import print_function
from __future__ import division
from __future__ import absolute_import

import argparse

import klupung
import klupung.models

arg_parser = argparse.ArgumentParser(
    description="Insert issue categories into a database.")

arg_parser.add_argument("db_uri", metavar="DB_URI",
                        help="database URI, e.g. 'sqlite:///klupung.db'")
arg_parser.add_argument("-q", "--quiet", default=False, action="store_true",
                        help="Do not print any output")

args = arg_parser.parse_args()

app = klupung.create_app(args.db_uri)
app.test_request_context().push()

category = klupung.models.Category("Kaikki", "00")
klupung.db.session.add(category)
klupung.db.session.commit()
