#!/usr/bin/env python
# KlupuNG
# Copyright (C) 2013 Koodilehto Osk <http://koodilehto.fi>.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

from __future__ import print_function
from __future__ import division
from __future__ import absolute_import

import argparse
import locale

import klupung
import klupung.models

arg_parser = argparse.ArgumentParser(
    description="Insert policymaker models to the database.")

arg_parser.add_argument("db_uri", metavar="DB_URI",
                        help="database URI, e.g. 'sqlite:///klupung.db'")
arg_parser.add_argument("abbreviation", metavar="ABBREVIATION",
                        help="policymaker abbreviation")
arg_parser.add_argument("name", metavar="NAME", help="policymaker name")

args = arg_parser.parse_args()

encoding = locale.getpreferredencoding()

app = klupung.create_app(args.db_uri)
app.test_request_context().push()

abbreviation = unicode(args.abbreviation.decode(encoding))
name = unicode(args.name.decode(encoding))

p = klupung.models.Policymaker(abbreviation, name)

klupung.db.session.add(p)
klupung.db.session.commit()
